name: clean_marketplace
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  get: 4.1.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  mockito: ^5.0.10
  flutter_test: 
    sdk: flutter
  build_runner: ^2.0.4

flutter: 
  uses-material-design: true

