// Mocks generated by Mockito 5.0.10 from annotations
// in clean_marketplace/test/domain/use_cases/get_customer_use_case_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:clean_marketplace/domain/entity/customer.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

import 'get_customer_use_case_test.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [CustomerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomerRepository extends _i1.Mock
    implements _i2.CustomerRepository {
  MockCustomerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Customer?> getCustomer() => (super.noSuchMethod(
      Invocation.method(#getCustomer, []),
      returnValue: Future<_i4.Customer?>.value()) as _i3.Future<_i4.Customer?>);
  @override
  String toString() => super.toString();
}
